stages:
  - build
  - dev
  - canary
  - master


build:
  stage: build
  image: 
    name: docker
  tags:
    - docker
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_TLS_CERTDIR: ""
  artifacts:
    paths:
      - ./
  before_script:
    - apk update && apk add gettext
  script:
  - echo $CI_COMMIT_TIMESTAMP | cut -d ":" -f 1-2 | sed 's/:/-/g' > Time.txt
  - TIME=$(cat Time.txt) 
  - export IMAGETAG="$CI_COMMIT_BRANCH"-"${TIME}"
  - export IMAGETAG="$CI_COMMIT_BRANCH"-"${TIME}"
  - sed -i 's|你的Docker帳號/cicd|你的Docker帳號/cicd:${IMAGETAG}|g' prod/b1-prod.yaml 
  - sed -i 's|你的Docker帳號/cicd|你的Docker帳號/cicd:${IMAGETAG}|g' dev/b1-dev.yaml
  - sed -i 's|你的Docker帳號/cicd|你的Docker帳號/cicd:${IMAGETAG}|g' canary/b1-canary.yaml
#範例  
# - sed -i 's|ragrag6326/cicd|ragrag6326/cicd:${IMAGETAG}|g' canary/b1-canary.yaml 

  - cat prod/b1-prod.yaml | envsubst | tee -a prod/prod.yaml > /dev/null
  - cat dev/b1-dev.yaml | envsubst | tee -a dev/dev.yaml > /dev/null
  - cat canary/b1-canary.yaml | envsubst | tee -a canary/canary.yaml  > /dev/null

  - docker login --username 你的Docker帳號 --password-stdin < ./dockerpasswd
  - docker build -t 你的Docker帳號/cicd:"${IMAGETAG}" .
  - docker images
  - docker push 你的Docker帳號/cicd:"${IMAGETAG}"


dev:
  stage: dev
  only:
    - dev
  image:
    name: bitnami/kubectl:latest 
    entrypoint: [""]
  tags:
    - docker
  script:
# - kubectl config get-contexts
  - kubectl config use-context devops/cicd:cicd
  - sed -i.bak 's#LoadBalancer#ClusterIP#' svc/service.yaml
  - kubectl get ns dev || kubectl create ns dev
  - kubectl apply -f svc/service.yaml -n dev
  - kubectl apply -f dev/dev.yaml -n dev

canary:
  stage: canary
  only:
    - canary
  image:
    name: bitnami/kubectl:latest 
    entrypoint: [""]
  tags:
    - docker
  script:
# - kubectl config get-contexts
  - kubectl config use-context devops/cicd:cicd
  - kubectl get ns prod || kubectl create ns prod
  - kubectl apply -f svc/service.yaml -n prod
  - kubectl apply -f canary/canary.yaml -n prod

prod:
  stage: master
  only:
    - master
  image:
    name: bitnami/kubectl:latest 
    entrypoint: [""]
  tags:
    - docker
  script:
# - kubectl config get-contexts
  - kubectl config use-context devops/cicd:cicd
  - kubectl get ns prod || kubectl create ns prod
  - kubectl apply -f svc/service.yaml -n prod
  - kubectl apply -f prod/prod.yaml -n prod




