kind: Deployment
apiVersion: apps/v1
metadata:
  name: b1-dev
spec:
  replicas: 
  selector:
    matchLabels:
      app: b1
      env: dev
  template:
    metadata:
      name: b1
      labels:
        app: b1
        env: dev
    spec:
      containers:
        - name: b1
          image: dockerac/cicd
          imagePullPolicy: Always
